### ISSUE TITLE
Request: down-list like navigation by C-M-d

### ISSUE THREAD

**Issue by tkf** [fgallina/python.el#112]
Hi, thanks for the up-list like navigation #111

Now it makes me wanting down-list :)

```
Scenario: Going lover level by C-M-u
    When I insert:
       """"
       class C(object):
           def m(self):
               if True:
                   return [i for i in range(3)]
               else:
                   return []
       """"
    And I am looking at "class C"
    And I press C-M-d
    Then I should looking at "def m"
    And I press C-M-d
    Then I should looking at "if True"
    And I press C-M-d
    Then I should looking at "i for i"
    And I press C-M-d
    Then I should looking at "3"
```

Current version of C-M-d jumps to inside of `(object)` because it is just a plain `down-list`.  I think it's better to have python-specific one for symmetry.

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
