### ISSUE TITLE
problem with python-indent-guess-indent-offset

### ISSUE THREAD

**Issue by yinhm** [fgallina/python.el#119]
Hi,

I have a problem with python-indent-guess-indent-offset.
- python-indent-offset set to 4
- When I opened another 3rd python file which is tab indented, python-indent-offset set to 8
- All buffer all indented by 8 now since python-indent-offset changed on the fly.
- I have to open another python to "guess" it right.

I know I can disable python-indent-guess-indent-offset, but I was thinking maybe there is a better way.

**Comment by joetxca** [comment]
Where can I find the config file to set offset?

**Comment by thyeun** [comment]
It only work for me with the below line.

```
(setq python-indent-guess-indent-offset-verbose nil)
```
