### ISSUE TITLE
Attributes are highlighted if the name matches built-in functions

### ISSUE THREAD

**Issue by Wilfred** [fgallina/python.el#126]
For example:

```
filter() # higlighted correctly
Foo.filter() # 'filter' highlighted with font-lock-builtin-face
```

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
