### ISSUE TITLE
fill-paragraph, python-fill-paragraph, and filladapt

### ISSUE THREAD

**Issue by tdavis** [fgallina/python.el#139]
I am having some trouble getting docstring fill-paragraph to work as designed. For instance, consider the following docstring:

```
"""
This is a docstring!

* Here is a list of stuff, this line is really long la la la la la la la. ..... . . ..... ... ... ... .. ..... ... ...
* Here is another item...

And stuff!
"""
```

My primary goal is to break up the long list item. Here are some observations:
- With `python-mode` and `filladapt` enabled, hitting `M-q` does nothing.
- `M-x python-fill-function` while on the long line wraps it as desired!
- Turning off `filladapt`, `M-q` collapses everything to a big block (but does wrap)

I haven't been able to take much away from this other than `python-fill-function` works but does not get executed by `M-q` (or `filladapt` doesn't like the return value)

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
