### ISSUE TITLE
Error line numbers not hyperlinked when using ipython

### ISSUE THREAD

**Issue by eigengrau** [fgallina/python.el#150]
When using ipython (1.1.0) with python.el (0.24.2), file-names and line-numbers shown in error messages are not clickable.

cpython, line with file name is a hyperlink:

```
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seb/xmlpy/example.py", line 18
    x =
      ^
SyntaxError: invalid syntax
```

ipython, line with file name is not a hyperlink:

```
In [4]:   File "/home/seb/xmlpy/example.py", line 18
    x =
       ^
SyntaxError: invalid syntax
```

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
