### ISSUE TITLE
Autocompletion does not work for magics with IPython

### ISSUE THREAD

**Issue by qbit-** [fgallina/python.el#155]
There is no autocompletion if one tries to type `ls ~/abc`.
The problem seems to be caused by stripping the original string 
from slashes and tilda characters. If one passes the "~/ab" sequence to 
the __PYTHON_EL_get_completions() from python.el completion works as expected,
but emacs passes "ab" instead

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
