### ISSUE TITLE
If your python.el supports open a python shell on remote host by tramp?

### ISSUE THREAD

**Issue by nannanmath** [fgallina/python.el#156]
HI, fgallina:
    Thank you for your python.el. 
    I am using emacs to develop python program with tramp on a remote host. I want to know if your python.el supports this function? That may mean that your python.el can create temporary file on remote host not local host.

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
