### ISSUE TITLE
please added the latest keywords(e.g. async, await) support for python3.5+

### ISSUE THREAD

**Issue by mxi1** [fgallina/python.el#157]
I find the newly-introduced keywords (e.g. async, await) cannot get the correct indentations in emacs, do you have any plans to add the support for new keywords? Thank you!

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report any issues using the Emacs command:

M-x report-emacs-bug

**Comment by mxi1** [comment]
Thanks for your reply.
