### ISSUE TITLE
I think it would be great if narrow-to-defun showed the function decorators too

### ISSUE THREAD

**Issue by Sukonnik-Illia** [fgallina/python.el#159]
When I narrow-to-defun, decorators of function are hidden.
I.e.:
```python
print('narrow-example')

@my_decorator
def f():
    pass

print('end-of-narrow-example')
```
narrowed to:
```python
def f():
    pass
```
But I think it should be:
```python
@my_decorator
def f():
    pass
```

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report this using the Emacs command:

M-x report-emacs-bug

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
