### ISSUE TITLE
IPython autocompletion stops working when assigning variable "dir"?

### ISSUE THREAD

**Issue by JoKeyser** [fgallina/python.el#160]
Hi,
let me first disclose I'm new to Emacs. My (weird) observation is that if you bind the (somewhat reserved) variable name *dir*, e.g. with *dir = 1*, then the Tab completion stops working.
Minimal example, all executed in an inferior IPython shell:
```
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: test = 1
In [2]: "te<TAB>" completes to "test"
In [2]: dir = 1
In [3]: "te<TAB>" says "No match"
```

Maybe relevant settings in my .emacs file are:
```elisp
(require 'python)
(setq python-shell-interpreter "ipython")
(setq python-shell-interpreter-args "console")
(setq python-shell-completion-native-enable nil)
```
My Emacs version is 25.2.1. Let me know if/how I can provide more details.

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report any issues using the Emacs command:

M-x report-emacs-bug

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
