### ISSUE TITLE
imenu does not show functions with return value annotations

### ISSUE THREAD

**Issue by glyph** [fgallina/python.el#161]
If I have a python file like this:

```
def foo():
    pass

def bar() -> int:
    pass

def baz():
    pass
```

both imenu and semantic see `foo` and `baz` but not `bar`.

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report any issues using the Emacs command:

M-x report-emacs-bug

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
