### ISSUE TITLE
Does not install on Emacs 24 & startup and runtime errors on Emacs 24

### ISSUE THREAD

**Issue by thjwong** [fgallina/python.el#162]
I use Devuan 1.0 (which is basically Debian Jessie sticks to Sys V).

It comes with Emacs 24.4, and I tried to installed via MELPA / ELPA at first: python-mode package did not install, and the error message was there is no package emacs 25.

Well, then I tried to install the package from the distribution's provided file by doing "sudo apt-get install python-mode". It installed successfully. but when I run it, there were errors and it was practically unusable:
In an opened Python file, and within the buffer typed C-c C-p. The Python window opened with an error message: 
`error in process filter: python-shell-send-file: Symbol's function definition is void: file-local-name`
`error in process filter: Symbol's function definition is void: file-local-name`
When I highlighted a region in the Python buffer and typed C-c C-r, nothing is sent to the Python process. And I received the following error message instead:
`Can't guess python-indent-offset, using defaults: 4`
`Sent: import sys...`
`python-shell-send-file: Symbol's function definition is void: file-local-name`
By the way, the highlighted region has no indent, and were some trivial things such as `import sys`. But the content of the Python buffer was not succesfully sent.
These issues happened to both python and python3.

The system admin may not be able to install Emacs 25 on this machine so soon as Emacs 25 has not been officially released yet for Devuan. Which meants it may need to break some dependencies to install Emacs 25 or to compile Emacs 25 from source.

Please let me know the possible work-around.

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report this using the Emacs command:

M-x report-emacs-bug

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
