### ISSUE TITLE
"Dummy completion" text printed when line contains `TABs`

### ISSUE THREAD

**Issue by smile13241324** [fgallina/python.el#164]
This is an issue reported originally in syl20bnr/spacemacs#11100.

When a line contains `TABs` the shell buffer shows some strange lines which looks like completion is tried. However in this case no completion is necessary, only the line has been indented with tabs.
I know this is just a small issue nevertheless it would be great if this could be fixed.

It can be reproduced by:
* Run `emacs -Q`
* `C-x` `C-f` `foo.py` `RET`.
* `M-x run-python` `RET`
* `M-: (setq indent-tabs-mode t)` `RET` (Spacemacs's python layer sets this setting.) 
* Press tab and return
* Notice the line `0__dummy_completion__ 1__dummy_completion__`

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report this using the Emacs command:

M-x report-emacs-bug
