### ISSUE TITLE
Weird error on Python script excecution

### ISSUE THREAD

**Issue by eamanu** [fgallina/python.el#165]
Hello!, 

I am running a simple line from emacs and I have a weird error:

![image](https://user-images.githubusercontent.com/7605307/45522993-f0f26a00-b79c-11e8-8007-153678b33bb3.png)

The line is:

`[ [raw_input(), float(raw_input())] for _ in range(int(raw_input()))]`

If I run this on a console that work successfully but from emacs not. 

I am running on a emacs 24.5.1

Regards!

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report this using the Emacs command:

M-x report-emacs-bug

**Comment by eamanu** [comment]
Hello, @skangas  Thanks very much. So, I will close this issue.
