### ISSUE TITLE
ipdb track buffer error

### ISSUE THREAD

**Issue by etern** [fgallina/python.el#167]
Steps:
1. `C-c, C-p` start ipython
2. `%run -d aaa.py` to start `ipdb`
3. enter `s` in ipdb, to step into bbb.py, track buffer is ok
4. enter `p xx` in ipdb, to print a value, **track buffer error**, current buffer `bbb.py` is closed

I checked the function `python-pdbtrack-comint-output-filter-function`, it handles comint output string like
`> /test/bbb.py(1239)function()`, if this kind of string is not matched, current buffer is killed.

https://github.com/fgallina/python.el/blob/9ba613269b5937b4be22b34f1ac5bb8cf050d5f3/python.el#L2368

pdb commands like `print`, `list` will not output file name and line number, when these commands are used, current buffer should not be killed.

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report this using the Emacs command:

M-x report-emacs-bug

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
