### ISSUE TITLE
Symbol’s value as variable is void: python-shell--interpreter-args

### ISSUE THREAD

**Issue by roymath-zz** [fgallina/python.el#168]
I'm using emacs-version: "27.1"

If I run` (inferior-python-mode)`, I get
 -> or: Symbol’s value as variable is void: python-shell--interpreter-args

This appears to be coming from
  ```
(set (make-local-variable 'python-shell-interpreter)
       (or python-shell--interpreter python-shell-interpreter))

```

**Comment by skangas** [comment]
Hi!

This repository is no longer maintained, since python-mode.el is now distributed with Emacs itself. I suggest that you report this using the Emacs command:

M-x report-emacs-bug

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
