### ISSUE TITLE
indent-region fails to indent first level of code set by python-indent-offset

### ISSUE THREAD

**Issue by onlinespending** [fgallina/python.el#170]
Say I have an existing, simple block of code that uses an indent width of 4, as such

```
def incDictValue(d, k):

    if not k in d:
        d[k] = 1
    else:
        d[k] += 1

    return
```

and setup python-mode in my init.el file to use a 2 space indent offset, like such

```
(add-hook 'python-mode-hook
  (lambda ()
    (setq python-indent-guess-indent-offset nil)
    (setq python-indent-offset 2)))
```

If I place the cursor on any line and hit TAB, the existing code is properly indented to match the indent offset of 2.

However, if I highlight the entire code block and M-x indent-region, only the second level indents are adjusted to 2. The first level indents (the 'if', 'else', and 'return' statements) are kept at 4.

```
def incDictValue(d, k):

    if not k in d:
      d[k] = 1
    else:
      d[k] += 1

    return
```

This clearly isn't the desired result that one would want when applying indent-region. Other major prog modes indent properly, so I have to imagine this is a bug with python.el.

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
