### ISSUE TITLE
Nested dictionary assignments syntax highlighted incorrectly

### ISSUE THREAD

**Issue by bradwright** [fgallina/python.el#32]
Like so:

```
event_transitions[data['period']] = right_now_iso8601
```

also functions in dictionaries:

```
event_transitions['%s-%s' % tuple(data['score'])] = right_now_iso8601
```

**Comment by fgallina** [comment]
Closing as I'm marking this repository as read only. To report bugs, or to contribute fixes and improvements, use the built-in Emacs bug reporter (M-x report-emacs-bug) or send an email to bug-gnu-emacs@gnu.org.
